### ISSUE TITLE
Maven error when jspc-maven-plugin >= 2.4.2, and maven 3.3.9 and dependency plugin 2.8

### ISSUE THREAD

**Issue by tcollignon** [leonardehrenfried/jspc-maven-plugin#20]
Hi,

I note an issue when I run the plugin with the following case : 

- Maven 3.3.9
- Maven dependency plugin : 2.8

I got this error :

```
[WARNING] Error injecting: org.apache.maven.artifact.installer.DefaultArtifactInstaller
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting: private org.eclipse.aether.spi.log.Logger org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger
  while locating org.apache.maven.repository.internal.DefaultVersionRangeResolver
  while locating java.lang.Object annotated with *
  at org.eclipse.sisu.wire.LocatorWiring
  while locating org.eclipse.aether.impl.VersionRangeResolver
    for parameter 2 at org.eclipse.aether.internal.impl.DefaultDependencyCollector.<init>(Unknown Source)
  while locating org.eclipse.aether.internal.impl.DefaultDependencyCollector
  while locating java.lang.Object annotated with *
  at org.eclipse.sisu.wire.LocatorWiring
  while locating org.eclipse.aether.impl.DependencyCollector
    for parameter 5 at org.eclipse.aether.internal.impl.DefaultRepositorySystem.<init>(Unknown Source)
  while locating org.eclipse.aether.internal.impl.DefaultRepositorySystem
  while locating java.lang.Object annotated with *
  while locating org.apache.maven.artifact.installer.DefaultArtifactInstaller
Caused by: java.lang.IllegalArgumentException: Can not set org.eclipse.aether.spi.log.Logger field org.apache.maven.repository.internal.DefaultVersionRangeResolver.logger to org.eclipse.aether.internal.impl.slf4j.Slf4jLoggerFactory
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.eclipse.sisu.bean.BeanPropertyField.set(BeanPropertyField.java:72)
	at org.eclipse.sisu.plexus.ProvidedPropertyBinding.injectProperty(ProvidedPropertyBinding.java:48)
	at `org.eclipse.sisu.bean.BeanInjector.injectMembers(BeanInjector.java:52)
```

It's work when : 

- I use Maven 3.5.X, and dependency plugin stay 2.8
- Or if change dependency plugin to 3.0.2, and stay Maven 3.3.9
- Or with jspc-maven-plugin 2.4.1

=> I think this commit 2549990f1f52e3f479c2353f83aefd9c773b cause this problem but I'm note sure.

What you think ?

- We do nothing
- We add FAQ in README to explain this and give workaround
- We try to fix this (decrease maven release plugin ?) Note we can add IT test to show that, if you can run this in Travis with maven 3.3.9

let me know

**Comment by tcollignon** [comment]
Note : even with maven dependency 3.0.2 there are still ohter injection error with maven 3.3.9.
I suggest to fix this so, to keep compatibility with maven 3.3.9

**Comment by leonardehrenfried** [comment]
Thanks for pointing it out. I must admit that my Maven knowledge is pretty out-of-date.

I'm happy downgrading the release plugin and I would be happy if you could make a suggestion on how to proceed.

I'm not really sure how much the different Maven versions are used.

**Comment by tcollignon** [comment]
Ok thx I will provide a PR with test and downgrading

**Comment by tcollignon** [comment]
see #21

**Comment by tcollignon** [comment]
Done by #21 => close
